export default function GoalWorkspaceStyles() {
  return <style jsx global>{`
/* Workspace surfaces. Data stays plain; borders and filled backgrounds mark controls. */
.wp-goal-sheet.goal-management.goal-workspace{display:flex;flex-direction:column;width:min(1140px,94vw);max-width:1140px;max-height:88dvh;padding:0;border-radius:18px;overflow:hidden;box-sizing:border-box}
.wp-goal-sheet.goal-management.goal-workspace.is-overview{height:auto;width:min(var(--overview-width),94vw)}.goal-workspace.is-detail{height:88dvh}
.goal-workspace .workspace-header{display:flex;justify-content:space-between;align-items:center;gap:16px;padding:16px 20px;border-bottom:1px solid var(--g-border);flex-shrink:0}
.goal-workspace .workspace-header h2{font:800 1.3rem/1.25 'Nunito',sans-serif;margin:0}.goal-workspace .workspace-header p{font-size:.76rem;color:var(--g-muted);margin:4px 0 0}
.goal-workspace .workspace-scroll{overflow:auto;padding:16px 20px;min-height:0;flex:1}
.goal-workspace .goal-management-layout{display:grid;grid-template-columns:200px minmax(0,1fr);gap:20px}.goal-workspace main{min-width:0}.goal-workspace aside{min-width:0;padding-right:16px;border-right:1px solid var(--g-border)}
.goal-workspace .overview-layout{display:block}.goal-workspace .overview-layout>aside{display:flex;align-items:center;justify-content:space-between;gap:12px;border:0;padding:0;margin-bottom:16px}
.goal-workspace .overview-layout>aside .goal-management-list,.goal-workspace .overview-layout>aside .mobile-goal-select,.goal-workspace .overview-layout>aside>p{display:none}
/* Button hierarchy */
.goal-workspace button{box-sizing:border-box;min-height:36px;border:1px solid var(--g-border);border-radius:9px;padding:8px 12px;background:var(--g-surface);color:var(--g-ink);font:700 .8rem/1.25 'Nunito',sans-serif;cursor:pointer;transition:background .16s,border-color .16s,box-shadow .16s,transform .16s}
.goal-workspace button:hover:not(:disabled){background:var(--g-bg);border-color:var(--g-a);box-shadow:0 2px 6px #0000000c}.goal-workspace button:active:not(:disabled){transform:translateY(1px)}
.goal-workspace button:disabled{opacity:.45;cursor:not-allowed;box-shadow:none}.goal-workspace button:focus-visible,.goal-workspace summary:focus-visible{outline:3px solid var(--g-a);outline-offset:3px}
.goal-workspace .workspace-header>button{width:36px;padding:0;font-size:1.2rem;border-radius:50%;background:var(--g-bg)}
.goal-workspace .workspace-primary,.goal-workspace .summary-open,.goal-workspace aside>button:last-child{background:var(--g-a);border-color:var(--g-a);color:var(--g-on)}
.goal-workspace .workspace-primary:hover:not(:disabled),.goal-workspace .summary-open:hover:not(:disabled),.goal-workspace aside>button:last-child:hover:not(:disabled){background:var(--g-a);filter:brightness(1.08)}
.goal-workspace nav{display:flex;flex-wrap:wrap;gap:4px;margin:0 0 12px}.goal-workspace .overview-layout nav{margin:0;background:var(--g-bg);padding:3px;border-radius:11px;border:1px solid var(--g-border)}
.goal-workspace nav button{white-space:nowrap;background:transparent;border-color:transparent;min-height:34px;padding:7px 10px;color:var(--g-muted)}.goal-workspace nav button[aria-pressed=true]{background:var(--g-surface);border-color:var(--g-border);color:var(--g-a);box-shadow:0 1px 4px #0000000b}
.goal-workspace .all-goals-button{width:100%;margin-bottom:12px;text-align:left}.goal-workspace .goal-management-list{display:grid;gap:6px;margin:0 0 12px}.goal-workspace .goal-management-list button{display:flex;align-items:flex-start;gap:8px;text-align:left;width:100%;padding:10px}.goal-workspace .goal-management-list b{font-size:.82rem;line-height:1.4}.goal-workspace .goal-management-list small{font-size:.68rem;display:block;margin-top:4px;color:var(--g-muted)}.goal-workspace .goal-management-list button[aria-pressed=true]{background:var(--g-bg);border-color:var(--g-a);box-shadow:inset 3px 0 var(--g-a)}.goal-workspace .mobile-goal-select{display:none}
/* Compact overview cards */
.goal-workspace .overview-intro{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:12px;font-size:.76rem;color:var(--g-muted)}.goal-workspace .overview-intro strong{color:var(--g-ink);font-weight:700}
.goal-workspace .all-goal-cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(290px,1fr));gap:14px;align-items:start}
.goal-workspace .goal-summary-card{min-width:0;border:1px solid var(--g-border);border-radius:14px;background:var(--g-surface);padding:16px;box-shadow:0 2px 8px #00000004}
.goal-workspace .summary-status{font-size:.68rem;font-weight:700;color:var(--g-muted);margin-bottom:6px}.goal-workspace .summary-title{display:flex;align-items:flex-start;gap:9px;margin-bottom:10px}.goal-workspace .summary-title>span{font-size:1.45rem;flex-shrink:0}.goal-workspace .summary-title h3{font:800 1.05rem/1.4 'Nunito',sans-serif;color:var(--g-ink);margin:0;overflow-wrap:anywhere}
.goal-workspace .summary-deadline{display:flex;flex-wrap:wrap;justify-content:space-between;gap:5px;font-size:.72rem;color:var(--g-muted);margin-bottom:12px}.goal-workspace .summary-deadline b{font-weight:700;color:var(--g-a)}
.goal-workspace .summary-progress{display:flex;justify-content:space-between;align-items:baseline;margin-bottom:5px}.goal-workspace .summary-progress strong{font-size:1.3rem;line-height:1.2;font-weight:800;color:var(--g-a)}.goal-workspace .summary-progress>span{font-size:.72rem;color:var(--g-muted)}
.goal-workspace .milestone-track{height:7px;background:var(--g-track);border-radius:99px;overflow:hidden}.goal-workspace .milestone-track i{display:block;height:100%;background:linear-gradient(90deg,var(--g-a),var(--g-a2));border-radius:inherit;transition:width .3s}
.goal-workspace .summary-metrics{display:grid;grid-template-columns:1fr 1fr;gap:12px;padding:12px 0;margin:0 0 10px;border-bottom:1px solid var(--g-border)}.goal-workspace .summary-metrics>div+div{border-left:1px solid var(--g-border);padding-left:12px}.goal-workspace .summary-metrics b{font-size:1rem;font-weight:800}.goal-workspace .summary-metrics small{display:block;font-size:.69rem;color:var(--g-muted);margin-top:2px}
.goal-workspace .summary-outcome{margin-bottom:10px}.goal-workspace .summary-outcome small,.goal-workspace .summary-next small{font-size:.65rem;letter-spacing:.03em;font-weight:800;color:var(--g-muted)}.goal-workspace .summary-outcome p,.goal-workspace .summary-next p{font-size:.81rem;line-height:1.5;margin:4px 0 0;overflow-wrap:anywhere}
.goal-workspace .summary-next{padding-left:9px;border-left:2px solid var(--g-a);margin:12px 0}.goal-workspace .summary-next small{color:var(--g-a)}
.goal-workspace .summary-milestone-details{margin:10px 0}.goal-workspace .summary-milestone-details summary{list-style:none;display:flex;align-items:center;justify-content:space-between;cursor:pointer;border:1px solid var(--g-border);border-radius:8px;padding:8px 10px;font-size:.73rem;font-weight:700;color:var(--g-ink);background:var(--g-bg);min-height:34px;box-sizing:border-box}.goal-workspace summary::-webkit-details-marker{display:none}.goal-workspace summary:hover{border-color:var(--g-a)}.goal-workspace details[open]>summary span{transform:rotate(180deg)}
.goal-workspace .summary-milestones{padding:0;list-style:none;margin:8px 0}.goal-workspace .summary-milestones li{display:flex;align-items:flex-start;gap:8px;padding:7px 0}.goal-workspace .summary-milestones li>span{display:grid;place-items:center;width:20px;height:20px;flex-shrink:0;border-radius:50%;background:var(--g-track);font-size:.65rem}.goal-workspace .summary-milestones li.next>span{background:var(--g-a);color:var(--g-on)}.goal-workspace .summary-milestones p{font-size:.78rem;line-height:1.5;margin:0}.goal-workspace .summary-milestones li.done{color:var(--g-muted)}
.goal-workspace .summary-open{width:100%;display:flex;align-items:center;justify-content:space-between;padding:10px 12px;min-height:38px}
/* Clearly labelled editable fields */
.goal-workspace .editing-hint{font-size:.73rem;color:var(--g-muted);margin:0 0 12px}.goal-workspace .goal-status{font-size:.7rem;color:var(--g-muted);margin:0 0 12px}
.goal-workspace input,.goal-workspace textarea,.goal-workspace select{font:400 .85rem/1.5 'Nunito',sans-serif;color:var(--g-ink);background:var(--g-surface);border:1px solid var(--g-border);border-radius:8px;padding:8px 10px;box-sizing:border-box;max-width:100%}
.goal-workspace input:hover,.goal-workspace textarea:hover{border-color:var(--g-a)}.goal-workspace input:focus,.goal-workspace textarea:focus,.goal-workspace select:focus{outline:2px solid var(--g-a);outline-offset:1px}.goal-workspace input:disabled,.goal-workspace textarea:disabled{opacity:.6;cursor:not-allowed}.theme-dark .goal-workspace input[type=date]{color-scheme:dark}
.goal-workspace .inline-goal-title{display:flex;gap:10px;margin-bottom:14px;align-items:start}.goal-workspace .inline-goal-title label>span{font-size:.69rem;font-weight:700;color:var(--g-muted);display:flex;justify-content:space-between;margin-bottom:5px}.goal-workspace .inline-goal-title label i{font-style:normal}.goal-workspace .emoji-field{width:65px;flex-shrink:0}.goal-workspace .emoji-field input{width:100%;font-size:1.4rem;text-align:center;padding:6px}.goal-workspace .title-field{flex:1;min-width:0}.goal-workspace .title-field textarea{width:100%;font-size:1.15rem;font-weight:800}
.goal-workspace .goal-overview{display:grid;grid-template-columns:180px minmax(0,1fr);gap:12px}.goal-workspace .deadline-card,.goal-workspace .outcome-card{display:flex;flex-direction:column;gap:5px;padding:0;background:none;border:0}.goal-workspace .deadline-card>span,.goal-workspace .outcome-card>span{font-size:.69rem;font-weight:700;color:var(--g-muted)}.goal-workspace .deadline-card strong{font-size:.72rem;color:var(--g-a)}.goal-workspace .outcome-card textarea{width:100%;min-height:70px;resize:vertical}
.goal-workspace .milestone-section{margin:20px 0}.goal-workspace .milestone-section>header{display:flex;justify-content:space-between;align-items:center;gap:10px;margin-bottom:10px}.goal-workspace .milestone-section header small{display:none}.goal-workspace .milestone-section h3{font:800 .95rem/1.3 'Nunito',sans-serif;margin:0}.goal-workspace .milestone-section header strong{font-size:.73rem;color:var(--g-muted)}
.goal-workspace .milestone-steps{display:grid;gap:8px;margin:12px 0}.goal-workspace .milestone-step{display:flex;align-items:center;gap:8px;border:0;border-left:2px solid var(--g-border);padding:5px 0 5px 8px}.goal-workspace .milestone-step.next{border-left-color:var(--g-a)}.goal-workspace .milestone-step>input{width:19px;height:19px;padding:0;accent-color:var(--g-a);flex-shrink:0;cursor:pointer}.goal-workspace .milestone-step>div{flex:1;min-width:0}.goal-workspace .milestone-step small{font-size:.65rem;font-weight:700;color:var(--g-muted);display:block;margin-bottom:4px}.goal-workspace .milestone-step.next small{color:var(--g-a)}.goal-workspace .milestone-step textarea{width:100%;display:block}.goal-workspace .milestone-step.complete textarea{color:var(--g-muted)}.goal-workspace .milestone-step>button{width:32px;min-height:32px;padding:0;color:var(--g-muted);font-size:1rem}
.goal-workspace .goal-management-actions{margin:12px 0;display:flex;gap:8px;flex-wrap:wrap}.goal-workspace .goal-ready,.goal-workspace .goal-achievement{background:color-mix(in srgb,var(--g-a2) 13%,var(--g-surface));border:1px solid var(--g-border);padding:14px;border-radius:12px;margin:12px 0;line-height:1.5}.goal-workspace .goal-ready{display:flex;justify-content:space-between;align-items:center;gap:10px;width:100%;font-size:.85rem}.goal-workspace .goal-achievement p{font-size:.83rem;margin:6px 0}.goal-workspace .goal-achievement small{color:var(--g-muted)}.goal-achievement.celebrate{animation:goalCelebrate .6s ease both}
.goal-workspace .goal-inline{max-width:none;border-radius:0}.goal-workspace .workspace-empty{padding:25px 12px;text-align:center;color:var(--g-muted)}
.goal-workspace .workspace-save{display:flex;align-items:center;gap:8px;flex-shrink:0;padding:12px 20px calc(12px + env(safe-area-inset-bottom));border-top:1px solid var(--g-border);background:var(--g-bg)}.goal-workspace .workspace-save>span{flex:1;font-size:.75rem;color:var(--g-muted)}.goal-workspace .workspace-error{font-size:.8rem;padding:10px 20px;margin:0;background:var(--g-track);color:var(--g-ink)}
@keyframes goalCelebrate{from{transform:scale(.98);opacity:.4}to{transform:none;opacity:1}}
@media(max-width:700px){
 .wp-goal-sheet.goal-management.goal-workspace{width:100%;max-width:none;max-height:92dvh;border-radius:16px 16px 0 0}.goal-workspace.is-detail{height:92dvh}.wp-goal-sheet.goal-management.goal-workspace.is-overview{height:auto;width:100%}
 .goal-workspace .workspace-header{padding:12px 14px}.goal-workspace .workspace-header h2{font-size:1.15rem}.goal-workspace .workspace-header p{font-size:.7rem}.goal-workspace .workspace-scroll{padding:12px 14px}
 .goal-workspace .goal-management-layout{grid-template-columns:1fr;gap:14px}.goal-workspace aside{padding:0 0 12px;border-right:0;border-bottom:1px solid var(--g-border)}.goal-workspace .goal-management-list{display:none}.goal-workspace .mobile-goal-select{display:block;width:100%;margin-bottom:10px}.goal-workspace .overview-layout>aside{flex-wrap:wrap;gap:8px;margin-bottom:10px}.goal-workspace .overview-layout nav{flex:1;flex-wrap:nowrap;min-width:0;gap:0}.goal-workspace .overview-layout nav button{padding:6px 8px;font-size:.72rem}.goal-workspace .overview-layout>aside>button:last-child{font-size:.75rem;padding:8px 10px}
 .goal-workspace .overview-intro{align-items:flex-start;flex-direction:column;gap:3px;margin-bottom:10px;font-size:.7rem}.goal-workspace .all-goal-cards{grid-template-columns:1fr;gap:10px}.goal-workspace .goal-summary-card{padding:13px}.goal-workspace .goal-overview{grid-template-columns:1fr}.goal-workspace .title-field textarea{font-size:1.05rem}.goal-workspace .workspace-save{padding:10px 14px calc(10px + env(safe-area-inset-bottom));flex-wrap:wrap}.goal-workspace .workspace-save>span{flex-basis:100%}.goal-workspace .workspace-save button{flex:1}.goal-workspace .goal-ready{flex-direction:column;align-items:flex-start}
}
@media(prefers-reduced-motion:reduce){.goal-workspace button,.goal-workspace .milestone-track i{transition:none}.goal-achievement.celebrate{animation:none}}
`}</style>;
}
